### ISSUE TITLE
How to use grid_spill Spill function?

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/GnomeTools#10]
Hi,

Currently, I'm trying to get grid_spill to work, but it gives empty images (No spill). This is the code I'm using:

```
spill = grid_spill(bounds=((west_lon, south_lat), (east_lon, north_lat)),
                           resolution=1,
                           release_time=start_time,
                           amount=5000,
                           units='bbl',
                           name="Grid")
```

But the images are all blank. point_line_release_spill, subsurface_plume_spill and spatial_release_spill are producing spills. Am I missing something here?

Thanks!

**Comment by ChrisBarker-NOAA** [comment]
grid_spill was recently refactored, so it *may* be broken. But I did notice:

`resolution=1,`

resolution is the number of points you want accross the box of yoru grid -- I"m not sure what 1 ill do, but it wont be much :-) -- try 20 or so and see if that works.

I"ll try to take another look on Monday.

**Comment by moisespr123** [comment]
Thanks! Changing the resolution made it work. BTW, just realized I opened the issue in the wrong repo 😅. Apologies for that.

**Comment by ChrisBarker-NOAA** [comment]
NP -- we're a small team :-) -- glad you worked it out.
